language: r
r:
  - oldrel
  - release
  - devel
r_github_packages:
  - hadley/devtools
warnings_are_errors: false
cache: packages
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_71b396cbdae4_key -iv $encrypted_71b396cbdae4_iv
  -in inst/extdata/sql.yaml.enc -out inst/extdata/sql.yaml -d
